/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";

export class InternalServerError extends errors.AzianmikeApiError {
    constructor(body?: unknown) {
        super({
            message: "InternalServerError",
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, InternalServerError.prototype);
    }
}
