/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class AzianmikeApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, AzianmikeApiTimeoutError.prototype);
    }
}
