/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import * as AzianmikeApi from "../../../api";
import * as core from "../../../core";

export const PostUsersRequest: core.serialization.Schema<
    serializers.PostUsersRequest.Raw,
    AzianmikeApi.PostUsersRequest
> = core.serialization.object({
    id: core.serialization.number().optional(),
    name: core.serialization.string().optional(),
});

export declare namespace PostUsersRequest {
    interface Raw {
        id?: number | null;
        name?: string | null;
    }
}
