/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as AzianmikeApi from "../../../../../api";
import * as core from "../../../../../core";

export const TrackUsageRequest: core.serialization.Schema<
    serializers.TrackUsageRequest.Raw,
    AzianmikeApi.TrackUsageRequest
> = core.serialization.object({
    key: core.serialization.string(),
    openAiResponse: core.serialization.lazyObject(async () => (await import("../../../..")).OpenAiResponse).optional(),
    usage: core.serialization.lazyObject(async () => (await import("../../../..")).UsageDetail).optional(),
});

export declare namespace TrackUsageRequest {
    interface Raw {
        key: string;
        openAiResponse?: serializers.OpenAiResponse.Raw | null;
        usage?: serializers.UsageDetail.Raw | null;
    }
}
