/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AzianmikeApi from "..";

export interface Choice {
    index: number;
    message: AzianmikeApi.Message;
    logprobs?: string;
    finishReason: string;
}
