/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AzianmikeApi from "..";

export interface OpenAiResponse {
    id: string;
    object: string;
    created: number;
    model: string;
    choices: AzianmikeApi.Choice[];
    usage: AzianmikeApi.UsageDetail;
    systemFingerprint?: string;
}
