/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AzianmikeApi from "../../../..";

export interface TrackUsageRequest {
    key: string;
    openAiResponse?: AzianmikeApi.OpenAiResponse;
    usage?: AzianmikeApi.UsageDetail;
}
