/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as AzianmikeApi from "../../api";
import * as core from "../../core";

export const Choice: core.serialization.ObjectSchema<serializers.Choice.Raw, AzianmikeApi.Choice> =
    core.serialization.object({
        index: core.serialization.number(),
        message: core.serialization.lazyObject(async () => (await import("..")).Message),
        logprobs: core.serialization.string().optional(),
        finishReason: core.serialization.property("finish_reason", core.serialization.string()),
    });

export declare namespace Choice {
    interface Raw {
        index: number;
        message: serializers.Message.Raw;
        logprobs?: string | null;
        finish_reason: string;
    }
}
