/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as AzianmikeApi from "../../api";
import * as core from "../../core";

export const Message: core.serialization.ObjectSchema<serializers.Message.Raw, AzianmikeApi.Message> =
    core.serialization.object({
        role: core.serialization.string(),
        content: core.serialization.string(),
    });

export declare namespace Message {
    interface Raw {
        role: string;
        content: string;
    }
}
