/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as AzianmikeApi from "../../api";
import * as core from "../../core";

export const OpenAiResponse: core.serialization.ObjectSchema<
    serializers.OpenAiResponse.Raw,
    AzianmikeApi.OpenAiResponse
> = core.serialization.object({
    id: core.serialization.string(),
    object: core.serialization.string(),
    created: core.serialization.number(),
    model: core.serialization.string(),
    choices: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).Choice)),
    usage: core.serialization.lazyObject(async () => (await import("..")).UsageDetail),
    systemFingerprint: core.serialization.property("system_fingerprint", core.serialization.string().optional()),
});

export declare namespace OpenAiResponse {
    interface Raw {
        id: string;
        object: string;
        created: number;
        model: string;
        choices: serializers.Choice.Raw[];
        usage: serializers.UsageDetail.Raw;
        system_fingerprint?: string | null;
    }
}
