/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import * as AzianmikeApi from "../../..";
import * as serializers from "../../../../serialization";
import urlJoin from "url-join";
import * as errors from "../../../../errors";

export declare namespace UsageTracking {
    interface Options {
        environment: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class UsageTracking {
    constructor(protected readonly _options: UsageTracking.Options) {}

    /**
     * @throws {@link AzianmikeApi.UnauthorizedError}
     * @throws {@link AzianmikeApi.InternalServerError}
     */
    public async trackUsage(
        request: AzianmikeApi.TrackUsageRequest,
        requestOptions?: UsageTracking.RequestOptions
    ): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(await core.Supplier.get(this._options.environment), "trackUsage"),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "test-analytics-sdk",
                "X-Fern-SDK-Version": "0.0.15",
            },
            contentType: "application/json",
            body: await serializers.TrackUsageRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new AzianmikeApi.UnauthorizedError(_response.error.body);
                case 500:
                    throw new AzianmikeApi.InternalServerError(_response.error.body);
                default:
                    throw new errors.AzianmikeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AzianmikeApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AzianmikeApiTimeoutError();
            case "unknown":
                throw new errors.AzianmikeApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getAuthorizationHeader() {
        const value = await core.Supplier.get(this._options.apiKey);
        if (value != null) {
            return value;
        }

        return undefined;
    }
}
